### ISSUE TITLE
Error initializing struct drm_framebuffer

### ISSUE THREAD

**Issue by loleg** [NVIDIA/open-gpu-kernel-modules#952]
### NVIDIA Open GPU Kernel Modules Version

6.17.4-200.fc42.x86_64

### Operating System and Version

Fedora 42

### Kernel Release

Upgrading from 6.16.12-200.fc42.x86_64

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Build Command

Failed during a standard system upgrade (`dnf upgrade`) including the kernel. Nvidia container toolkit also updated.

### Terminal output/Build Log

```
[ 8/41] Upgrading nvidia-container-toolkit-base-0:1.18.0-1.x86_64                                               100% |  12.4 MiB/s |  24.5 MiB |  00m02s
>>> Running %post scriptlet: nvidia-container-toolkit-base-0:1.18.0-1.x86_64                                                                            
>>> Finished %post scriptlet: nvidia-container-toolkit-base-0:1.18.0-1.x86_64                                                                           
>>> Scriptlet output:                                                                                                                                   
>>> Created symlink '/etc/systemd/system/multi-user.target.wants/nvidia-cdi-refresh.path' → '/etc/systemd/system/nvidia-cdi-refresh.path'.              
>>> Created symlink '/etc/systemd/system/multi-user.target.wants/nvidia-cdi-refresh.service' → '/etc/systemd/system/nvidia-cdi-refresh.service'.        
>>> Regenerating NVIDIA CDI specification...                                                                                                            
>>>                                                                                                                                                     
[ 9/41] Upgrading libnvidia-container1-0:1.18.0-1.x86_64     
```

This worked fine .. but later on:

```
>>> Running %posttrans scriptlet: kernel-core-0:6.17.4-200.fc42.x86_64                                                                                  
>>> Finished %posttrans scriptlet: kernel-core-0:6.17.4-200.fc42.x86_64                                                                                 
>>> Scriptlet output:                                                                                                                                   
>>> Sign command: /lib/modules/6.17.4-200.fc42.x86_64/build/scripts/sign-file                                                                           
>>> Signing key: /var/lib/dkms/mok.key                                                                                                                  
>>> Public certificate (MOK): /var/lib/dkms/mok.pub                                                                                                     
>>>                                                                                                                                                     
>>> Autoinstall of module nvidia/575.57.08 for kernel 6.17.4-200.fc42.x86_64 (x86_64)                                                                   
>>> Building module(s).......................(bad exit status: 2)                                                                                       
>>> Failed command:                                                                                                                                     
>>> 'make' -j6 KERNEL_UNAME=6.17.4-200.fc42.x86_64 modules                                                                                              
>>>                                                                                                                                                     
>>> Error! Bad return status for module build on kernel: 6.17.4-200.fc42.x86_64 (x86_64)                                                                
>>> Consult /var/lib/dkms/nvidia/575.57.08/build/make.log for more information.                                                                         
>>>                                                                                                                                                     
>>> Autoinstall on 6.17.4-200.fc42.x86_64 failed for module(s) nvidia(10).                                                                              
>>>                                                                                                                                                     
>>> Error! One or more modules failed to install during autoinstall.                                                                                    
>>> Refer to previous errors for more information. 
```

Pertinent excerpt from the above log:

```
CC [M]  nvidia-drm/nvidia-drm-gem.o
nvidia-drm/nvidia-drm-drv.c:240:18: error: initialization of ‘struct drm_framebuffer * (*)(struct drm_device *, struct drm_file *, const struct drm_format_info *, const struct drm_mode_fb_cmd2 *)’ from incompatible pointer type ‘struct drm_framebuffer * (*)(struct drm_device *, struct drm_file *, const struct drm_mode_fb_cmd2 *)’ [-Wincompatible-pointer-types]
  240 |     .fb_create = nv_drm_framebuffer_create,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
nvidia-drm/nvidia-drm-drv.c:240:18: note: (near initialization for ‘nv_mode_config_funcs.fb_create’)
nvidia-drm/nvidia-drm-drv.c:212:32: note: ‘nv_drm_framebuffer_create’ declared here
  212 | static struct drm_framebuffer *nv_drm_framebuffer_create(
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [/usr/src/kernels/6.17.4-200.fc42.x86_64/scripts/Makefile.build:287: nvidia-drm/nvidia-drm-drv.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/kernels/6.17.4-200.fc42.x86_64/Makefile:2047: .] Error 2
make[2]: *** [/usr/src/kernels/6.17.4-200.fc42.x86_64/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/nvidia/575.57.08/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.17.4-200.fc42.x86_64'
make: *** [Makefile:140: modules] Error 2
```

### More Info

Possibly related to #917

**Comment by loleg** [comment]
Apologies in advance if I'm posting in the wrong repo :)

**Comment by Binary-Eater** [comment]
@loleg would you mind sharing what NVIDIA driver release version you are using?

**Comment by Binary-Eater** [comment]
Nevermind, I see it in the logs. 575.57.08

The required kernel compatibility changes are not present in this older driver release. Can you try our latest production driver release?

**Comment by loleg** [comment]
Seems to work fine. Thank you
