### ISSUE TITLE
nvidia-uvm/uvm_gpu.c:4110:1: error: label at end of compound statement

### ISSUE THREAD

**Issue by ocstx** [NVIDIA/open-gpu-kernel-modules#1390]
### NVIDIA Open GPU Kernel Modules Version

615.71.09

### Operating System and Version

AlmaLinux release 8.10 (Cerulean Leopard)

### Kernel Release

4.18.0-553.164.1.el8_10.x86_64

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Build Command

dkms autoinstall -k 7.2.7-1.el8.elrepo.x86_64
dkms autoinstall -k 7.0.6-1.el8.elrepo.x86_64
dkms autoinstall -k 7.0.4-1.el8.elrepo.x86_64

### Terminal output/Build Log

```
[root@brizard ~]# dkms autoinstall -k 7.2.7-1.el8.elrepo.x86_64                                                                                                     
Sign command: /lib/modules/7.2.7-1.el8.elrepo.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Autoinstall of module nvidia/615.71.09 for kernel 7.2.7-1.el8.elrepo.x86_64 (x86_64)                                                                                
Building module(s)..........(bad exit status: 2)
Failed command:
'make' -j32 KERNEL_UNAME=7.2.7-1.el8.elrepo.x86_64 IGNORE_PREEMPT_RT_PRESENCE=1 IGNORE_XEN_PRESENCE=1 modules                                                       

Error! Bad return status for module build on kernel: 7.2.7-1.el8.elrepo.x86_64 (x86_64)                                                                             
Consult /var/lib/dkms/nvidia/615.71.09/build/make.log for more information.

Autoinstall on 7.2.7-1.el8.elrepo.x86_64 failed for module(s) nvidia(10).

Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.

```

### More Info

The system was running kernel-ml 7.06 from elrepo-kernel. It work with nvidia driver 610.57.04
after `dnf update` it updated to 615.71.09 and stop working.
I updated to the newest kernel-ml and the same error was obtained.
I moved to the oficial almalinux 8 latest kernel (4.18.0-553.164.1.el8_10.x86_64) and I managed to build it with the dkms autoinstall command. 
I tested all other kernel-ml 7 that I have installed and all report the same error: (I'm pasting here the last lines from `/var/lib/dkms/nvidia/615.71.09/build/make.log `, which are the ones that contain the error):

```
 CC [M]  nvidia-uvm/uvm_gpu_non_replayable_faults.o
nvidia-uvm/uvm_gpu.c: In function ‘uvm_gpu_map_cpu_pages_for_egm’:
nvidia-uvm/uvm_gpu.c:4110:1: error: label at end of compound statement
 done:
 ^~~~
  CC [M]  nvidia-uvm/uvm_gpu_access_counters.o
  CC [M]  nvidia-uvm/uvm_perf_events.o
  CC [M]  nvidia-uvm/uvm_perf_module.o
nvidia-uvm/uvm_gpu.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-alloc-size-larger-than’
make[5]: *** [/usr/src/kernels/7.2.7-1.el8.elrepo.x86_64/scripts/Makefile.build:289: nvidia-uvm/uvm_gpu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/usr/src/kernels/7.2.7-1.el8.elrepo.x86_64/Makefile:2198: .] Error 2
make[3]: *** [/usr/src/kernels/7.2.7-1.el8.elrepo.x86_64/Makefile:248: __sub-make] Error 2
make[3]: Leaving directory '/var/lib/dkms/nvidia/615.71.09/build/kernel-open'
make[2]: *** [Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/kernels/7.2.7-1.el8.elrepo.x86_64'
make[1]: *** [Makefile:115: modules] Error 2
make[1]: Leaving directory '/var/lib/dkms/nvidia/615.71.09/build/kernel-open'
make: *** [Makefile:59: modules] Error 2

# exit code: 2
# elapsed time: 00:00:24
----------------------------------------------------------------
```
