### ISSUE TITLE
580.159.04+ fails to build (unused variable ‘chip’)

### ISSUE THREAD

**Issue by timbertson** [NVIDIA/open-gpu-kernel-modules#1377]
### NVIDIA Open GPU Kernel Modules Version

b81d58ee0224d1d290bef1c080592b619e184042

### Operating System and Version

Fedora release 44

### Kernel Release

Linux pew 7.2.5-200.fc44.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 11 15:11:05 UTC 2026 x86_64 GNU/Linux

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Build Command

```
sudo akmods --force
```

### Terminal output/Build Log

```
2026/09/20 12:03:17 akmods: Building RPM using the command '/usr/sbin/akmodsbuild --kernels 7.2.5-200.fc44.x86_64 /usr/src/akmods/nvidia-580xx-kmod.latest'
 1785 |         struct gpio_chip *chip = gpio_device_get_chip(gdev);
      |                           ^~~~
# CC [M]  nvidia/nv-kthread-q.o
  gcc -Wp,-MMD,nvidia/.nv-kthread-q.o.d -nostdinc -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/generated/uapi -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler-version.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/kconfig.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler_types.h -D__KERNEL__ -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -std=gnu11 -fms-extensions -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-sse4a -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=x86-64 -mtune=generic -mno-red-zone -mcmodel=kernel -mstack-protector-guard-reg=gs -mstack-protector-guard-symbol=__ref_stack_chk_guard -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -ftrivial-auto-var-init=zero -fzero-init-padding-bits=all -fno-stack-clash-protection -fdiagnostics-show-context=2 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -fno-builtin-wcslen -Wall -Wextra -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-type-limits -Wno-dangling-pointer -Wvla-larger-than=1 -Wno-pointer-sign -Wcast-function-type -Wno-unterminated-string-initialization -Wno-array-bounds -Wno-stringop-overflow -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -I././common/inc -I./. -Wall -Wno-cast-qual -Wno-format-extra-args -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"580.159.04\" -DNV_FILESYSTEM_ACCESS_AVAILABLE=1 -Wno-unused-function -Wuninitialized -fno-strict-aliasing -ffreestanding -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE -Werror=undef -DNV_SPECTRE_V2=0 -DNV_KERNEL_INTERFACE_LAYER -Wno-error -I././nvidia -DNVIDIA_UNDEF_LEGACY_BIT_MACROS -UDEBUG -U_DEBUG -DNDEBUG  -fsanitize=bounds-strict -fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"nv_kthread_q"' -DKBUILD_MODNAME='"nvidia"' -D__KBUILD_MODNAME=nvidia -c -o nvidia/nv-kthread-q.o nvidia/nv-kthread-q.c  
# CC [M]  nvidia/os-registry.o
  gcc -Wp,-MMD,nvidia/.os-registry.o.d -nostdinc -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/generated/uapi -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler-version.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/kconfig.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler_types.h -D__KERNEL__ -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -std=gnu11 -fms-extensions -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-sse4a -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=x86-64 -mtune=generic -mno-red-zone -mcmodel=kernel -mstack-protector-guard-reg=gs -mstack-protector-guard-symbol=__ref_stack_chk_guard -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -ftrivial-auto-var-init=zero -fzero-init-padding-bits=all -fno-stack-clash-protection -fdiagnostics-show-context=2 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -fno-builtin-wcslen -Wall -Wextra -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-type-limits -Wno-dangling-pointer -Wvla-larger-than=1 -Wno-pointer-sign -Wcast-function-type -Wno-unterminated-string-initialization -Wno-array-bounds -Wno-stringop-overflow -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -I././common/inc -I./. -Wall -Wno-cast-qual -Wno-format-extra-args -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"580.159.04\" -DNV_FILESYSTEM_ACCESS_AVAILABLE=1 -Wno-unused-function -Wuninitialized -fno-strict-aliasing -ffreestanding -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE -Werror=undef -DNV_SPECTRE_V2=0 -DNV_KERNEL_INTERFACE_LAYER -Wno-error -I././nvidia -DNVIDIA_UNDEF_LEGACY_BIT_MACROS -UDEBUG -U_DEBUG -DNDEBUG  -fsanitize=bounds-strict -fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"os_registry"' -DKBUILD_MODNAME='"nvidia"' -D__KBUILD_MODNAME=nvidia -c -o nvidia/os-registry.o nvidia/os-registry.c  
In file included from nvidia/os-registry.c:27:
././common/inc/nv-linux.h: In function ‘of_get_named_gpio’:
././common/inc/nv-linux.h:1785:27: warning: unused variable ‘chip’ [-Wunused-variable]
 1785 |         struct gpio_chip *chip = gpio_device_get_chip(gdev);
      |                           ^~~~
# CC [M]  nvidia/os-usermap.o
  gcc -Wp,-MMD,nvidia/.os-usermap.o.d -nostdinc -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/generated/uapi -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler-version.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/kconfig.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler_types.h -D__KERNEL__ -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -std=gnu11 -fms-extensions -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-sse4a -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=x86-64 -mtune=generic -mno-red-zone -mcmodel=kernel -mstack-protector-guard-reg=gs -mstack-protector-guard-symbol=__ref_stack_chk_guard -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -ftrivial-auto-var-init=zero -fzero-init-padding-bits=all -fno-stack-clash-protection -fdiagnostics-show-context=2 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -fno-builtin-wcslen -Wall -Wextra -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-type-limits -Wno-dangling-pointer -Wvla-larger-than=1 -Wno-pointer-sign -Wcast-function-type -Wno-unterminated-string-initialization -Wno-array-bounds -Wno-stringop-overflow -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -I././common/inc -I./. -Wall -Wno-cast-qual -Wno-format-extra-args -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"580.159.04\" -DNV_FILESYSTEM_ACCESS_AVAILABLE=1 -Wno-unused-function -Wuninitialized -fno-strict-aliasing -ffreestanding -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE -Werror=undef -DNV_SPECTRE_V2=0 -DNV_KERNEL_INTERFACE_LAYER -Wno-error -I././nvidia -DNVIDIA_UNDEF_LEGACY_BIT_MACROS -UDEBUG -U_DEBUG -DNDEBUG  -fsanitize=bounds-strict -fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"os_usermap"' -DKBUILD_MODNAME='"nvidia"' -D__KBUILD_MODNAME=nvidia -c -o nvidia/os-usermap.o nvidia/os-usermap.c  
In file included from nvidia/os-usermap.c:27:
././common/inc/nv-linux.h: In function ‘of_get_named_gpio’:
././common/inc/nv-linux.h:1785:27: warning: unused variable ‘chip’ [-Wunused-variable]
 1785 |         struct gpio_chip *chip = gpio_device_get_chip(gdev);
      |                           ^~~~
# CC [M]  nvidia/nv-pci-table.o
  gcc -Wp,-MMD,nvidia/.nv-pci-table.o.d -nostdinc -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/generated/uapi -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler-version.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/kconfig.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler_types.h -D__KERNEL__ -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -std=gnu11 -fms-extensions -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-sse4a -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=x86-64 -mtune=generic -mno-red-zone -mcmodel=kernel -mstack-protector-guard-reg=gs -mstack-protector-guard-symbol=__ref_stack_chk_guard -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -ftrivial-auto-var-init=zero -fzero-init-padding-bits=all -fno-stack-clash-protection -fdiagnostics-show-context=2 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -fno-builtin-wcslen -Wall -Wextra -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-type-limits -Wno-dangling-pointer -Wvla-larger-than=1 -Wno-pointer-sign -Wcast-function-type -Wno-unterminated-string-initialization -Wno-array-bounds -Wno-stringop-overflow -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -I././common/inc -I./. -Wall -Wno-cast-qual -Wno-format-extra-args -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"580.159.04\" -DNV_FILESYSTEM_ACCESS_AVAILABLE=1 -Wno-unused-function -Wuninitialized -fno-strict-aliasing -ffreestanding -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE -Werror=undef -DNV_SPECTRE_V2=0 -DNV_KERNEL_INTERFACE_LAYER -Wno-error -I././nvidia -DNVIDIA_UNDEF_LEGACY_BIT_MACROS -UDEBUG -U_DEBUG -DNDEBUG  -fsanitize=bounds-strict -fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"nv_pci_table"' -DKBUILD_MODNAME='"nvidia"' -D__KBUILD_MODNAME=nvidia -c -o nvidia/nv-pci-table.o nvidia/nv-pci-table.c  
# CC [M]  nvidia/nv-modeset-interface.o
  gcc -Wp,-MMD,nvidia/.nv-modeset-interface.o.d -nostdinc -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/arch/x86/include/generated/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/uapi -I/usr/src/kernels/7.2.5-200.fc44.x86_64/include/generated/uapi -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler-version.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/kconfig.h -include /usr/src/kernels/7.2.5-200.fc44.x86_64/include/linux/compiler_types.h -D__KERNEL__ -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -std=gnu11 -fms-extensions -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-sse4a -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=x86-64 -mtune=generic -mno-red-zone -mcmodel=kernel -mstack-protector-guard-reg=gs -mstack-protector-guard-symbol=__ref_stack_chk_guard -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -ftrivial-auto-var-init=zero -fzero-init-padding-bits=all -fno-stack-clash-protection -fdiagnostics-show-context=2 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -fno-builtin-wcslen -Wall -Wextra -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-type-limits -Wno-dangling-pointer -Wvla-larger-than=1 -Wno-pointer-sign -Wcast-function-type -Wno-unterminated-string-initialization -Wno-array-bounds -Wno-stringop-overflow -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -I././common/inc -I./. -Wall -Wno-cast-qual -Wno-format-extra-args -D__KERNEL__ -DMODULE -DNVRM -DNV_VERSION_STRING=\"580.159.04\" -DNV_FILESYSTEM_ACCESS_AVAILABLE=1 -Wno-unused-function -Wuninitialized -fno-strict-aliasing -ffreestanding -mno-red-zone -mcmodel=kernel -DNV_UVM_ENABLE -Werror=undef -DNV_SPECTRE_V2=0 -DNV_KERNEL_INTERFACE_LAYER -Wno-error -I././nvidia -DNVIDIA_UNDEF_LEGACY_BIT_MACROS -UDEBUG -U_DEBUG -DNDEBUG  -fsanitize=bounds-strict -fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"nv_modeset_interface"' -DKBUILD_MODNAME='"nvidia"' -D__KBUILD_MODNAME=nvidia -c -o nvidia/nv-modeset-interface.o nvidia/nv-modeset-interface.c  
In file included from nvidia/nv-modeset-interface.c:27:
././common/inc/nv-linux.h: In function ‘of_get_named_gpio’:
././common/inc/nv-linux.h:1785:27: warning: unused variable ‘chip’ [-Wunused-variable]
 1785 |         struct gpio_chip *chip = gpio_device_get_chip(gdev);
      |                           ^~~~
make[3]: *** [/usr/src/kernels/7.2.5-200.fc44.x86_64/Makefile:2228: .] Error 2
make[2]: *** [/usr/src/kernels/7.2.5-200.fc44.x86_64/Makefile:248: __sub-make] Error 2
make[1]: *** [Makefile:248: __sub-make] Error 2
make: *** [Makefile:115: modules] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.oKNtSI (%build)

# (output truncated, github said it was too long...)

2026/09/20 12:03:47 akmods: Building rpms failed; see /var/cache/akmods/nvidia-580xx/580.159.04-1-for-7.2.5-200.fc44.x86_64.failed.log for details
```

### More Info

Looks like the variable is only used if `CONFIG_OF_GPIO` is defined. I haven't been able to disable fatal warnings, so this won't build even though it's just a warning.

**Comment by alshdavid** [comment]
I just put in a newly purchased 5080 into my PC and ran into this issue on Fedora 44

```
$ uname -a
Linux DALSH-DESKTOP-LINUX 7.2.6-200.fc44.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 14 22:22:41 UTC 2026 x86_64 GNU/Linux
```

To install I ran
```bash
sudo dnf install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf install akmod-nvidia-open # I guess this is the same as akmod-nvidia?
sudo dnf install xorg-x11-drv-nvidia-cuda

# Reboot
sudo akmods --force

Checking kmods exist for 7.2.6-200.fc44.x86_64 [  OK  ]
Building and installing nvidia-open-kmod [FAILED]
Building rpms failed; see /var/cache/akmods/nvidia-open/595.58.03-2-for-7.2.6-200.fc44.x86_64.failed.log for details

Hint: Some kmods were ignored or failed to build or install.
You can try to rebuild and install them by by calling
'/usr/sbin/akmods --force' as root.
```

**Comment by aritger** [comment]
Thanks for the report.  This was temporarily broken and then fixed, but 580.159.04 caught the snapshot in between.

Releases 595.104.02 and 615.71.09, for example, should have the fix.  Our next 580.xx release should have the fix, too.

I apologize for the inconvenience.

**Comment by aritger** [comment]
Actually, I misspoke in my previous comment:
- The breakage I referred to was the `warning: unused variable ‘chip’`.  That's a legitimate warning, and is fixed in the versions I mentioned.  But I don't think the Fedora 44 kernel enables warnings-as-errors (CONFIG_WERROR).  So that warning wouldn't explain your installation failure.
- @timbertson's log was truncated due to github restrictions. As I understand it, 580.159.04 will fail to build against Linux kernel 7.2 due to `implicit declaration of function ‘strncpy’` and `implicit declaration of function ‘drm_atomic_state_alloc’; did you mean ‘nv_drm_atomic_state_alloc’`.  Both of those failures should already be fixed in the latest 580 release, 580.178.04.
- @alshdavid 's failure is due to using 595.58.03, which we expect to fail to build against Linux kernel 7.2 due with an error `fatal error: linux/of_gpio.h: No such file or directory`.

In both cases, using the latest 580 release, 595.178.04, is expected to work with Fedora 44's Linux kernel 7.2.  Please let me know if you find problems with that combination.

**Comment by alshdavid** [comment]
Thanks. Driver install works on Fedora 45 beta but I can't daily drive it for work. On fc44, I don't want to mess around with swapping kernels or hand picking drivers. 

I guess I'll just wait for the official Fedora release of fc45 next month and, in the meantime, I'll use Nouveau on fc44 and put my AMD 9070xt into my second PCI slot to use for ML and gaming until then.

This was my first nvidia purchase, was really excited to migrate my ROCm workloads to CUDA but I guess the rumors about nvidia-linux compatibility were true 🤣
